apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-reverse-proxy-config
data:
  nginx.conf: |
    events { }

    http {
      server {
        listen 80;

        location / {
          proxy_pass http://service-test:5000/;
        }
      }
    }
