kind: Service
apiVersion: v1
metadata:
  name: service-test
spec:
  selector:
    myname: sonu  # Ensure this matches labels in your Pods/Deployment
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP  
